# Generated by Django 5.0.6 on 2024-07-10 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_delete_attendance_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('username', models.CharField(default='username', max_length=255)),
                ('DateOfBirth', models.DateField()),
                ('Tel', models.CharField(blank=True, max_length=13, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('DateOfChurchEntry', models.DateField()),
                ('DateOfCellEntry', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('isAttended', models.BooleanField(blank=True, default=False, null=True)),
                ('DateAttended', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.usermodel')),
            ],
        ),
    ]
