# Generated by Django 5.0.6 on 2024-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='slug',
        ),
        migrations.AddField(
            model_name='attendance',
            name='topic',
            field=models.CharField(default='topic here', max_length=255),
        ),
    ]
