# Generated by Django 5.0.6 on 2024-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_slug_attendance_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
