# Generated by Django 5.0.6 on 2024-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='isLate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
