# Generated by Django 5.0.6 on 2024-08-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_remove_attendance_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='isAttended',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='isLate',
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='ABSENT', max_length=10),
        ),
    ]
