# Generated by Django 5.0.6 on 2024-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='DateAttended',
            field=models.DateField(auto_now_add=True),
        ),
    ]
