# Generated by Django 5.0.6 on 2024-08-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_attendance_dateattended'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
